import 'server-only';
import manifest from '@/lib/photos.json';
import type { PhotoData } from '@/lib/photo-data';

export type { PhotoData };
export { placeholderStyle } from '@/lib/photo-data';

// Generated by `npm run images` (scripts/build-images.mjs).
export type PhotoName = keyof typeof manifest;

/** Everything an <img> needs for a photo: the master, its smaller copies, and the placeholder. */
export function photo(name: PhotoName): PhotoData {
  const { width, height, widths, color, blur } = manifest[name];
  const copies = widths.map((w) => `/images/${name}-${w}.webp ${w}w`);
  return {
    src: `/images/${name}.webp`,
    srcSet: [...copies, `/images/${name}.webp ${width}w`].join(', '),
    width,
    height,
    color,
    blur,
  };
}
