// English copy. Uses the owner's English wording from marrakech-riads.com/en where it exists,
// and faithful translations of the French page elsewhere (the tea ritual has no English original).
import type { Dictionary } from './fr';

export const en: Dictionary = {
  meta: {
    title: 'Dar Zellij · Moroccan restaurant in a 17th-century riad, Marrakech',
    description:
      'Fine Moroccan dining in a 17th-century riad in the Marrakech medina: painted ceilings, menu and set menus, rooftop, evenings and reservations.',
  },
  a11y: {
    skip: 'Skip to content',
    home: 'Dar Zellij, back to top',
    primaryNav: 'Main navigation',
    language: 'Language',
    openMenu: 'Open the menu',
    closeMenu: 'Close the menu',
    newTab: '(new tab)',
  },
  nav: {
    links: [
      { id: 'riad', label: 'The riad' },
      { id: 'ritual', label: 'The ritual' },
      { id: 'menu', label: 'The menu' },
      { id: 'rooftop', label: 'The rooftop' },
      { id: 'week', label: 'Hours' },
    ],
    book: 'Book',
    menu: 'Menu',
    close: 'Close',
  },
  status: {
    open: 'Open · until midnight',
    later: 'Opens today at 12pm',
    closed: 'Closed on Tuesdays · reopens Wednesday at 12pm',
    dancer: 'Tonight: belly dancer',
    brunch: 'Brunch from 11am, on request',
  },
  preloader: { est: 'Est. 1999', city: 'Marrakech' },
  hero: {
    title: 'Dar Zellij',
    tagline: '17th-century Moroccan restaurant',
  },
  intro: {
    kicker: 'Since 1999',
    statement:
      'Of all the buildings Marrakech Riads has restored, Dar Zellij stands as *one of the most remarkable.*',
    aside:
      'This beautiful dwelling has been transformed into a high-end Moroccan restaurant, where guests can taste true Moroccan cuisine in an incomparable atmosphere.',
    facts: [
      {
        value: '17^th^',
        label: 'century',
        text: 'A riad in the medina that still preserves its original painted ceilings.',
      },
      {
        value: '2016',
        label: 'La Liste',
        text: 'Named one of the best restaurants in the world.',
      },
    ],
  },
  riad: {
    kicker: 'The riad',
    title: 'A *17^th^-century* riad',
    text: 'In this extraordinary 17th-century riad, which still preserves its original painted ceilings of rare beauty, we have created a unique and compelling ambience, both luxurious and romantic, for an enchanting, timeless journey.',
    hint: 'Keep scrolling',
    roomsLabel: 'The rooms of the riad',
    rooms: [
      {
        photo: 'patio',
        name: 'The patio',
        text: 'Columns, trees and laid tables at the heart of the house.',
      },
      {
        photo: 'painted-ceiling',
        name: 'The painted ceilings',
        text: 'The original decoration, of rare beauty.',
      },
      {
        photo: 'salon-fireplace',
        name: 'The salons',
        text: 'A fireplace, chandeliers and candlelight.',
      },
      {
        photo: 'alcove-table',
        name: 'The alcoves',
        text: 'Tables laid beneath carved arches.',
      },
      {
        photo: 'rooftop-view',
        name: 'The rooftop',
        text: 'Above the rooftops of the medina.',
      },
    ],
  },
  ritual: {
    kicker: 'The ritual',
    photosLabel: 'Photos of the ritual',
    beats: [
      {
        text: 'Teapots are raised high to pour the steaming tea into the glasses,',
        photo: 'tea-pour',
      },
      { text: 'the musicians play a few light notes,', photo: 'red-salon' },
      { text: 'and the round of dishes can begin…', photo: 'tagine-reveal' },
    ],
  },
  menu: {
    kicker: 'Taste Morocco on a plate',
    title: 'The *menu*',
    signature: {
      label: 'Signature dishes',
      text: 'Moroccan dishes to share, including trid and mechoui: ancient recipes passed down from generation to generation, reflecting the rich history and culinary heritage of our country.',
      forTwo: 'For two people',
    },
    chapters: {
      starters: 'Starters',
      mains: 'Mains',
      desserts: 'Desserts',
      menus: 'Set menus',
      cocktails: 'Cocktails',
      wines: 'Wines',
      drinks: 'Drinks',
    },
    courses: { starter: 'Starter', main: 'Main', dessert: 'Dessert' },
    perPerson: 'per person',
    or: 'or',
    continued: 'continued',
    drinks: {
      title: 'Drinks menu',
      signature: 'Signature cocktails',
      classics: 'Classic cocktails',
      mocktails: 'Mocktails & smoothies',
      wines: 'Our Moroccan wines',
      hot: 'Hot drinks',
    },
    tagineNote:
      'All our tagines are served with semolina or seasonal vegetables.',
    currency: 'Prices in Moroccan dirhams (MAD).',
    book: {
      label: 'The Dar Zellij menu',
      chaptersLabel: 'Menu chapters',
      open: 'Open the menu',
      close: 'Close the menu',
      prev: 'Previous page',
      next: 'Next page',
      hint: 'Drag the pages to turn them.',
      cover: 'Cover',
      backCover: 'Back cover',
      status: '{pages} · {n} of {total}',
    },
  },
  rooftop: {
    kicker: 'The rooftop',
    title: 'Above the *rooftops* of the medina',
    text: 'The rooftop terrace overlooks the roofs of Marrakech. On the drinks menu: signature cocktails with Taliouine saffron, fig or date, and Moroccan wines.',
    cocktails: 'Signature cocktails',
  },
  week: {
    kicker: 'Opening hours',
    title: 'The *week* at Dar Zellij',
    text: 'Open every day except Tuesday, from 12pm to midnight.',
    days: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    hours: '12pm – 12am',
    closed: 'Closed',
    dancer: 'Belly dancer evening',
    brunch: 'Brunch from 11am, on request',
    today: 'Today',
  },
  gallery: {
    kicker: 'Gallery',
    title: 'In *pictures*',
    text: 'The patio, the salons, the rooftop and the table.',
    open: 'Enlarge',
    close: 'Close',
    prev: 'Previous photo',
    next: 'Next photo',
    dialog: 'Photo gallery',
  },
  book: {
    kicker: 'Reservations',
    title: 'Book your *table*',
    text: 'Send us your request and we will reply to confirm your table.',
    details: {
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      instagram: 'Instagram',
      hours: 'Hours',
      directions: 'Directions',
    },
    hoursLines: [
      'Every day except Tuesday, 12pm – midnight',
      'Sunday brunch from 11am, on request',
    ],
    form: {
      date: 'Date',
      time: 'Time',
      guests: 'Guests',
      guestsMore: 'More than 12',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      message: 'Message',
      optional: 'optional',
      messageHint: 'An occasion, an allergy, a preference…',
      submit: 'Send request',
      closedDay:
        'The restaurant is closed on Tuesdays: please choose another day.',
      pastDate: 'Please choose a date from today onwards.',
      required: 'Please fill in this field.',
      invalidEmail: 'Please enter a valid email address.',
      choose: 'Choose',
      pickDate: 'Choose a date',
      prevMonth: 'Previous month',
      nextMonth: 'Next month',
      today: 'Today',
      closedLegend: 'Closed on Tuesdays',
      closedShort: 'closed',
      closeCalendar: 'Close the calendar',
      closeList: 'Close the list',
      brunch: 'brunch',
      success:
        'Thank you, {name}. We will reply to {email} to confirm your table.',
      summary: '{guests} · {date} at {time}',
      guest: 'guest',
      guestsPlural: 'guests',
      again: 'New request',
    },
  },
  sisters: {
    kicker: 'Marrakech Riads',
    title: 'Our other *tables*',
    text: 'Two more Marrakech Riads houses, in Marrakech and in Fes.',
    cta: 'Discover',
    items: [
      {
        name: 'Restaurant Dar Cherifa',
        city: 'Marrakech',
        photo: 'dar-cherifa',
        url: 'https://marrakech-riads.com/en/restaurant-dar-cherifa/',
      },
      {
        name: 'Table d’Hôtes Dar Bensouda',
        city: 'Fes',
        photo: 'dar-bensouda',
        url: 'https://marrakech-riads.com/en/table-dhotes-dar-bensouda/',
      },
    ],
  },
  closing: {
    title: 'Taste Morocco *on a plate*',
    text: 'An enchanting, timeless journey in the heart of the Marrakech medina.',
    book: 'Book a table',
    call: 'Call the restaurant',
  },
  footer: {
    tagline: '17th-century Moroccan restaurant',
    est: 'Est. 1999 · Marrakech',
    explore: 'Explore',
    find: 'Find us',
    hours: 'Hours',
    hoursLines: [
      'Every day except Tuesday',
      '12pm – midnight',
      'Sunday brunch from 11am, on request',
      'Belly dancer on Thursdays and Sundays',
    ],
    group: 'A Marrakech Riads house',
    time: 'Marrakech',
    top: 'Back to top',
    book: 'Book a table',
  },
  dock: {
    label: 'Book or call',
    book: 'Book a table',
    bookShort: 'Book',
    call: 'Call',
  },
  cursor: { view: 'View' },
};
